#spring.application.name=Gabriel Donation Campaign

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gabriel?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        column_ordering_strategy: legacy
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false